- name: Create VLAN
  hosts: '{{ host }}'
  gather_facts: no
  tasks:

  - name: Create VLAN in '{{net_name}}'
    meraki_vlan:
      auth_key: '{{auth_key}}'
      state: present
      org_name: '{{org_name}}'
      net_name: '{{net_name}}'
      vlan_id: '{{vlan_id}}'
      name: '{{vlan_name}}'
      subnet: '{{subnet}}'
      appliance_ip: '{{gateway_ip}}'
    delegate_to: localhost
    register: create_vlan
    environment:
      ANSIBLE_MERAKI_FORMAT: snakecase

  - debug:
      msg: '{{create_vlan}}'
