- hosts: localhost
  tasks:
    - name: Query all devices in an organization.
      meraki_device:
        dashboard: dashboard.meraki.com
        auth_key: '{{ MERAKI_KEY }}'
        org_name: JRTECHNOLOGY
        state: query
      delegate_to: localhost
