- name: SW-JRTECHNO-01 Port(8) Configuration
  hosts: '{{ host }}'
  gather_facts: no
  tasks:
  - name: Port(8) Configuration
    connection: localhost
    meraki_switchport:
      name: '{{ name }}'
      state: present
      poe_enabled: '{{ poe_enabled }}'
      number: '8'
      enabled: '{{ enabled }}'
      type: '{{ type }}'
      vlan: '{{ vlan }}'
      allowed_vlans: '{{ allowed_vlans }}'
      isolation_enabled: '{{ isolation_enabled }}'
      rstp_enabled: '{{ rstp_enabled }}'
      stp_guard: '{{ stp_guard }}'
      link_negotiation: '{{ link_negotiation }}'
      auth_key: '{{ auth_key }}'
      serial: '{{ serial_number }}'
    delegate_to: localhost
