- name: Name Port(8) on SW-JRTECHNO-01
  hosts: dashboard.meraki.com
  gather_facts: no
  tasks:
  - name: Name switchport 8 Label
    connection: localhost
    meraki_switchport:
      state: present
      auth_key: '{{ auth_key }}'
      serial: Q2BX-MWD9-HKGU
      number: '8'
      name: Empty
    delegate_to: localhost
